# Add application configuration variables here, as shown below.
DATABASEDOTCOM_USERNAME: externalappuser@rocketfuel.com.full
DATABASEDOTCOM_PASSWORD: passwordhere
DATABASEDOTCOM_SECURITY_TOKEN: L9WdHbvVszoZEUFSbwmrOvTc
DATABASEDOTCOM_CLIENT_ID: 3MVG9PerJEe9i8iKookjMaMTE6auO4lzf8dF0vSztEMUtVbVtlFm6nDGqiNQZD31pCIgDp_UkipYkXcb0sXi7
DATABASEDOTCOM_CLIENT_SECRET: 'secrethere'
DATABASEDOTCOM_HOST: test.salesforce.com

JIRA_API: https://jira.rocketfuel.com
JIRA_USER: robbie
JIRA_PASS: passwordhere
JIRA_DEFAULT_USER: robbie

# JIRA_API: http://jira.rocketfuel.com
# JIRA_USER: robbie
# JIRA_PASS: DdNk6coO03JVha
# JIRA_DEFAULT_USER: apiuser
# development: 
#   JIRA_DEFAULT_USER: apiuser

GMAIL_USER: icf-jira@rocketfuelinc.com
GMAIL_PASS: passwordhere

CALLOUT: .
MINMARGIN: 61%
MAXMARGIN: 90%
MINCPM: $0.10
MAXCPM: $0.40

DESCR_PREFIX: |
    Remember--use the workflow buttons above to move this JIRA forward.
    Do not manually reassign this JIRA unless checked with your ICF champion.

DESCR_SUFFIX: |
    - See all your ICF campaigns on the Kanban board: <http://is.gd/gUve2O>
    - See the ICF user group for docs and any questions: <http://is.gd/cbVtcu>
    - Get notified about the latest ICF changes: install the Yammer app
      for mobile <http://goo.gl/TYvnlw> or Windows <http://goo.gl/GFPbVV>

EMAIL_BATCH_SIZE: '1'

ERROR_MONITOR_ADDRESS: roland+icf_errors@rocketfuelinc.com
AM_SUBSTITUTE_ADDRESS: roland+icf_am_error@rocketfuelinc.com

